# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Joe Frambach
email: hello@framba.ch
description: 'A travelogue, technologue, tutelogue.'
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://joe.framba.ch" # the base hostname & protocol for your site
twitter_username: joeframbach
github_username:  joeframbach
permalink: /:categories/:slug

collections:
  projects:
    output: true
    permalink: /projects/:slug

# Build settings
markdown: kramdown

kramdown:
  input: GFM
  hard_wrap: false
